export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  BAD_REQUEST = 'BAD_REQUEST',

  APPOINTMENT_ALREADY_BOOKED = 'APPOINTMENT_ALREADY_BOOKED',
  APPOINTMENT_NOT_FOUND = 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_INVALID_STATUS = 'APPOINTMENT_INVALID_STATUS',

  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',

  PATIENT_NOT_FOUND = 'PATIENT_NOT_FOUND',
  DOCTOR_NOT_FOUND = 'DOCTOR_NOT_FOUND',
  MEDICAL_RECORD_NOT_FOUND = 'MEDICAL_RECORD_NOT_FOUND',
  ACCESS_DENIED = 'ACCESS_DENIED',
}
